import { PublicKey, type AccountMeta, type TransactionInstruction } from "@solana/web3.js";
import { StateCheckpointPhaseV1 } from "./release1.js";
import { fixedInstruction, ro, rs, rw, ws } from "./release1FixedWire.js";
import {
  type ApproveEmergencyResolutionV2, type ApproveProposalV3, type ApproveUnfreezeV2,
  type BindProgramDataVerificationV2, type CancelProposalV3, type CreateCheckpointV2,
  type CreateEmergencyResolutionV2, type CreateProposalV3, type ExecuteEmergencyResolutionV2,
  type ExecuteUnfreezeV2, type ExpireEmergencyResolutionV2, type ExpireProposalV3,
  type FinalizeCheckpointV2, type FinalizeGovernanceV3, type FinalizeProgramDataVerificationV2,
  type FreezeProposalV3, type GuardianFreezeV2, type InitializeControllerV2,
  type ObserveProgramDataFailureV2, type QueueEmergencyResolutionV2, type QueueProposalV3,
  type RecastCheckpointV2,
  encodeApproveEmergencyResolutionV2, encodeApproveProposalV3, encodeApproveUnfreezeV2,
  encodeBindProgramDataVerificationV2, encodeCancelProposalV3, encodeCreateCheckpointV2,
  encodeCreateEmergencyResolutionV2, encodeCreateProposalV3, encodeExecuteEmergencyResolutionV2,
  encodeExecuteUnfreezeV2, encodeExpireEmergencyResolutionV2, encodeExpireProposalV3,
  encodeFinalizeCheckpointV2, encodeFinalizeGovernanceV3, encodeFinalizeProgramDataVerificationV2,
  encodeFreezeProposalV3, encodeGuardianFreezeV2, encodeInitializeControllerV2,
  encodeObserveProgramDataFailureV2, encodeQueueEmergencyResolutionV2, encodeQueueProposalV3,
  encodeRecastCheckpointV2,
} from "./release1V3Instructions.js";

export interface InitializeControllerV2Accounts {
  payer: PublicKey; initializer: PublicKey; controllerProgram: PublicKey; controllerProgramdata: PublicKey;
  targetProgram: PublicKey; targetProgramdata: PublicKey; upgradeableLoader: PublicKey; controllerConfig: PublicKey;
  authorityPda: PublicKey; protocolGate: PublicKey; policy: PublicKey; council: PublicKey; capacityPolicy: PublicKey;
  controllerRelease: PublicKey; canonicalSpillTreasury: PublicKey; guardian: PublicKey;
  seatAuthorities: readonly PublicKey[]; systemProgram: PublicKey;
}
export interface CreateProposalV3Accounts {
  payer: PublicKey; creatorSeatAuthority: PublicKey; controllerConfig: PublicKey; policy: PublicKey; council: PublicKey;
  protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; targetProgram: PublicKey;
  targetProgramdata: PublicKey; upgradeableLoader: PublicKey; authorityPda: PublicKey; canonicalSpillTreasury: PublicKey;
  buffer: PublicKey; bufferUploaderAuthority: PublicKey; proposal: PublicKey; systemProgram: PublicKey;
}
export interface ApproveProposalV3Accounts { controllerConfig: PublicKey; policy: PublicKey; creationCouncil: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; proposal: PublicKey; bufferVerification: PublicKey; seatAuthority: PublicKey }
export type FinalizeGovernanceV3Accounts = Omit<ApproveProposalV3Accounts, "bufferVerification" | "seatAuthority">;
export interface QueueProposalV3Accounts { controllerConfig: PublicKey; policy: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; proposal: PublicKey }
export interface FreezeProposalV3Accounts { controllerConfig: PublicKey; policy: PublicKey; creationCouncil: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; proposal: PublicKey; targetProgram: PublicKey; targetProgramdata: PublicKey; upgradeableLoader: PublicKey; authorityPda: PublicKey; rollbackProposal: PublicKey; rollbackBufferVerification: PublicKey; rollbackBuffer: PublicKey }
export interface CancelProposalV3Accounts { controllerConfig: PublicKey; policy: PublicKey; currentCouncil: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; proposal: PublicKey; seatAuthority: PublicKey }
export interface ExpireProposalV3Accounts { controllerConfig: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; proposal: PublicKey }
export interface GuardianFreezeV2Accounts { payer: PublicKey; controllerConfig: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; targetProgram: PublicKey; targetProgramdata: PublicKey; upgradeableLoader: PublicKey; authorityPda: PublicKey; guardian: PublicKey; emergencyFreezeObservation: PublicKey; systemProgram: PublicKey }
export interface CreateEmergencyResolutionV2Accounts { payer: PublicKey; creatorSeatAuthority: PublicKey; controllerConfig: PublicKey; policy: PublicKey; currentCouncil: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; emergencyFreezeObservation: PublicKey; programdataObservation: PublicKey; emergencyResolution: PublicKey; systemProgram: PublicKey }
export interface ApproveEmergencyResolutionV2Accounts { controllerConfig: PublicKey; policy: PublicKey; currentCouncil: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; emergencyFreezeObservation: PublicKey; programdataObservation: PublicKey; emergencyCheckpoint: PublicKey; emergencyResolution: PublicKey; seatAuthority: PublicKey }
export type QueueEmergencyResolutionV2Accounts = Omit<ApproveEmergencyResolutionV2Accounts, "seatAuthority">;
export interface ExecuteEmergencyResolutionV2Accounts { controllerConfig: PublicKey; policy: PublicKey; currentCouncil: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; emergencyResolution: PublicKey; emergencyFreezeObservation: PublicKey; programdataObservation: PublicKey; emergencyCheckpoint: PublicKey; targetProgram: PublicKey; targetProgramdata: PublicKey; upgradeableLoader: PublicKey; authorityPda: PublicKey; instructionsSysvar: PublicKey }
export interface ExpireEmergencyResolutionV2Accounts { controllerConfig: PublicKey; protocolGate: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; emergencyResolution: PublicKey }
export interface CreateCheckpointV2Accounts { payer: PublicKey; controllerConfig: PublicKey; policy: PublicKey; currentCouncil: PublicKey; protocolGate: PublicKey; subject: PublicKey; linkedPrimaryOrAuthority: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; programdataObservation: PublicKey; targetProgram: PublicKey; targetProgramdata: PublicKey; checkpoint: PublicKey; checkpointAttestation: PublicKey; seatAuthority: PublicKey; systemProgram: PublicKey }
export type RecastCheckpointV2Accounts = Omit<CreateCheckpointV2Accounts, "payer" | "systemProgram">;
export interface FinalizeCheckpointV2Accounts { payer: PublicKey; controllerConfig: PublicKey; policy: PublicKey; currentCouncil: PublicKey; protocolGate: PublicKey; subject: PublicKey; linkedPrimaryOrAuthority: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; programdataObservation: PublicKey; targetProgram: PublicKey; targetProgramdata: PublicKey; checkpoint: PublicKey; checkpointAttestations: readonly PublicKey[]; systemProgram: PublicKey }
export interface BindProgramDataVerificationV2Accounts { payer: PublicKey; controllerConfig: PublicKey; protocolGate: PublicKey; proposal: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; programdataObservation: PublicKey; targetProgram: PublicKey; targetProgramdata: PublicKey; authorityPda: PublicKey; upgradeableLoader: PublicKey; programdataVerification: PublicKey; systemProgram: PublicKey }
export type FinalizeProgramDataVerificationV2Accounts = Omit<BindProgramDataVerificationV2Accounts, "payer" | "systemProgram">;
export interface ObserveProgramDataFailureV2Accounts { payer: PublicKey; controllerConfig: PublicKey; protocolGate: PublicKey; primaryProposal: PublicKey; programdataVerification: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; programdataObservation: PublicKey; targetProgram: PublicKey; targetProgramdata: PublicKey; authorityPda: PublicKey; upgradeableLoader: PublicKey; failureObservation: PublicKey; systemProgram: PublicKey }
export interface ApproveUnfreezeV2Accounts { controllerConfig: PublicKey; policy: PublicKey; currentCouncil: PublicKey; protocolGate: PublicKey; proposal: PublicKey; poststateCheckpoint: PublicKey; programdataVerification: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; targetProgram: PublicKey; targetProgramdata: PublicKey; authorityPda: PublicKey; upgradeableLoader: PublicKey; seatAuthority: PublicKey }
export interface ExecuteUnfreezeV2Accounts { controllerConfig: PublicKey; policy: PublicKey; currentCouncil: PublicKey; protocolGate: PublicKey; proposal: PublicKey; linkedProposal: PublicKey; poststateCheckpoint: PublicKey; programdataVerification: PublicKey; capacityPolicy: PublicKey; currentDeployment: PublicKey; targetProgram: PublicKey; targetProgramdata: PublicKey; authorityPda: PublicKey; upgradeableLoader: PublicKey; instructionsSysvar: PublicKey }

const ix = (programId: PublicKey, keys: readonly AccountMeta[], data: Buffer): TransactionInstruction => fixedInstruction(programId, keys, data);
export const buildInitializeControllerV2Instruction = (p: PublicKey, a: InitializeControllerV2Accounts, v: InitializeControllerV2): TransactionInstruction => {
  if (a.seatAuthorities.length !== 5) throw new Error("InitializeControllerV2 requires exactly five seat authorities");
  return ix(p, [ws(a.payer), rs(a.initializer), ro(a.controllerProgram), ro(a.controllerProgramdata), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.upgradeableLoader), rw(a.controllerConfig), ro(a.authorityPda), rw(a.protocolGate), rw(a.policy), rw(a.council), rw(a.capacityPolicy), rw(a.controllerRelease), ro(a.canonicalSpillTreasury), ro(a.guardian), ...a.seatAuthorities.map(ro), ro(a.systemProgram)], encodeInitializeControllerV2(v));
};
export const buildCreateProposalV3Instruction = (p: PublicKey, a: CreateProposalV3Accounts, v: CreateProposalV3): TransactionInstruction => ix(p, [ws(a.payer), rs(a.creatorSeatAuthority), rw(a.controllerConfig), ro(a.policy), ro(a.council), ro(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.upgradeableLoader), ro(a.authorityPda), ro(a.canonicalSpillTreasury), ro(a.buffer), ro(a.bufferUploaderAuthority), rw(a.proposal), ro(a.systemProgram)], encodeCreateProposalV3(v));
export const buildApproveProposalV3Instruction = (p: PublicKey, a: ApproveProposalV3Accounts, v: ApproveProposalV3): TransactionInstruction => ix(p, [ro(a.controllerConfig), ro(a.policy), ro(a.creationCouncil), ro(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), rw(a.proposal), ro(a.bufferVerification), rs(a.seatAuthority)], encodeApproveProposalV3(v));
export const buildFinalizeGovernanceV3Instruction = (p: PublicKey, a: FinalizeGovernanceV3Accounts, v: FinalizeGovernanceV3): TransactionInstruction => ix(p, [ro(a.controllerConfig), ro(a.policy), ro(a.creationCouncil), ro(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), rw(a.proposal)], encodeFinalizeGovernanceV3(v));
export const buildQueueProposalV3Instruction = (p: PublicKey, a: QueueProposalV3Accounts, v: QueueProposalV3): TransactionInstruction => ix(p, [ro(a.controllerConfig), ro(a.policy), ro(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), rw(a.proposal)], encodeQueueProposalV3(v));
export const buildFreezeProposalV3Instruction = (p: PublicKey, a: FreezeProposalV3Accounts, v: FreezeProposalV3): TransactionInstruction => ix(p, [rw(a.controllerConfig), ro(a.policy), ro(a.creationCouncil), rw(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), rw(a.proposal), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.upgradeableLoader), ro(a.authorityPda), ro(a.rollbackProposal), ro(a.rollbackBufferVerification), ro(a.rollbackBuffer)], encodeFreezeProposalV3(v));
export const buildCancelProposalV3Instruction = (p: PublicKey, a: CancelProposalV3Accounts, v: CancelProposalV3): TransactionInstruction => ix(p, [ro(a.controllerConfig), ro(a.policy), ro(a.currentCouncil), ro(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), rw(a.proposal), rs(a.seatAuthority)], encodeCancelProposalV3(v));
export const buildExpireProposalV3Instruction = (p: PublicKey, a: ExpireProposalV3Accounts, v: ExpireProposalV3): TransactionInstruction => ix(p, [ro(a.controllerConfig), ro(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), rw(a.proposal)], encodeExpireProposalV3(v));
export const buildGuardianFreezeV2Instruction = (p: PublicKey, a: GuardianFreezeV2Accounts, v: GuardianFreezeV2): TransactionInstruction => ix(p, [ws(a.payer), ro(a.controllerConfig), rw(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.upgradeableLoader), ro(a.authorityPda), rs(a.guardian), rw(a.emergencyFreezeObservation), ro(a.systemProgram)], encodeGuardianFreezeV2(v));
export const buildCreateEmergencyResolutionV2Instruction = (p: PublicKey, a: CreateEmergencyResolutionV2Accounts, v: CreateEmergencyResolutionV2): TransactionInstruction => ix(p, [ws(a.payer), rs(a.creatorSeatAuthority), ro(a.controllerConfig), ro(a.policy), ro(a.currentCouncil), ro(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.emergencyFreezeObservation), ro(a.programdataObservation), rw(a.emergencyResolution), ro(a.systemProgram)], encodeCreateEmergencyResolutionV2(v));
const emergencyApprovalKeys = (a: QueueEmergencyResolutionV2Accounts): AccountMeta[] => [ro(a.controllerConfig), ro(a.policy), ro(a.currentCouncil), ro(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.emergencyFreezeObservation), ro(a.programdataObservation), ro(a.emergencyCheckpoint), rw(a.emergencyResolution)];
export const buildApproveEmergencyResolutionV2Instruction = (p: PublicKey, a: ApproveEmergencyResolutionV2Accounts, v: ApproveEmergencyResolutionV2): TransactionInstruction => ix(p, [...emergencyApprovalKeys(a), rs(a.seatAuthority)], encodeApproveEmergencyResolutionV2(v));
export const buildQueueEmergencyResolutionV2Instruction = (p: PublicKey, a: QueueEmergencyResolutionV2Accounts, v: QueueEmergencyResolutionV2): TransactionInstruction => ix(p, emergencyApprovalKeys(a), encodeQueueEmergencyResolutionV2(v));
export const buildExecuteEmergencyResolutionV2Instruction = (p: PublicKey, a: ExecuteEmergencyResolutionV2Accounts, v: ExecuteEmergencyResolutionV2): TransactionInstruction => ix(p, [ro(a.controllerConfig), ro(a.policy), ro(a.currentCouncil), rw(a.protocolGate), ro(a.capacityPolicy), rw(a.currentDeployment), rw(a.emergencyResolution), ro(a.emergencyFreezeObservation), ro(a.programdataObservation), ro(a.emergencyCheckpoint), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.upgradeableLoader), ro(a.authorityPda), ro(a.instructionsSysvar)], encodeExecuteEmergencyResolutionV2(v));
export const buildExpireEmergencyResolutionV2Instruction = (p: PublicKey, a: ExpireEmergencyResolutionV2Accounts, v: ExpireEmergencyResolutionV2): TransactionInstruction => ix(p, [ro(a.controllerConfig), ro(a.protocolGate), ro(a.capacityPolicy), ro(a.currentDeployment), rw(a.emergencyResolution)], encodeExpireEmergencyResolutionV2(v));

const checkpointBase = (a: RecastCheckpointV2Accounts): AccountMeta[] => [ro(a.controllerConfig), ro(a.policy), ro(a.currentCouncil), ro(a.protocolGate), ro(a.subject), ro(a.linkedPrimaryOrAuthority), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.programdataObservation), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.checkpoint), rw(a.checkpointAttestation), rs(a.seatAuthority)];
export const buildCreateCheckpointV2Instruction = (p: PublicKey, a: CreateCheckpointV2Accounts, v: CreateCheckpointV2): TransactionInstruction => ix(p, [ws(a.payer), ...checkpointBase(a), ro(a.systemProgram)], encodeCreateCheckpointV2(v));
export const buildRecastCheckpointV2Instruction = (p: PublicKey, a: RecastCheckpointV2Accounts, v: RecastCheckpointV2): TransactionInstruction => ix(p, checkpointBase(a), encodeRecastCheckpointV2(v));
export const buildFinalizeCheckpointV2Instruction = (p: PublicKey, a: FinalizeCheckpointV2Accounts, v: FinalizeCheckpointV2): TransactionInstruction => {
  if (a.checkpointAttestations.length !== 3) throw new Error("FinalizeCheckpointV2 requires exactly three attestations");
  const subject = v.manifest.phase === StateCheckpointPhaseV1.Prestate ? ro(a.subject) : rw(a.subject);
  return ix(p, [ws(a.payer), ro(a.controllerConfig), ro(a.policy), ro(a.currentCouncil), ro(a.protocolGate), subject, ro(a.linkedPrimaryOrAuthority), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.programdataObservation), ro(a.targetProgram), ro(a.targetProgramdata), rw(a.checkpoint), ...a.checkpointAttestations.map(ro), ro(a.systemProgram)], encodeFinalizeCheckpointV2(v));
};
export const buildBindProgramDataVerificationV2Instruction = (p: PublicKey, a: BindProgramDataVerificationV2Accounts, v: BindProgramDataVerificationV2): TransactionInstruction => ix(p, [ws(a.payer), ro(a.controllerConfig), ro(a.protocolGate), ro(a.proposal), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.programdataObservation), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.authorityPda), ro(a.upgradeableLoader), rw(a.programdataVerification), ro(a.systemProgram)], encodeBindProgramDataVerificationV2(v));
const finalizeVerificationKeys = (a: FinalizeProgramDataVerificationV2Accounts): AccountMeta[] => [ro(a.controllerConfig), ro(a.protocolGate), rw(a.proposal), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.programdataObservation), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.authorityPda), ro(a.upgradeableLoader), rw(a.programdataVerification)];
export const buildFinalizeProgramDataVerificationV2Instruction = (p: PublicKey, a: FinalizeProgramDataVerificationV2Accounts, v: FinalizeProgramDataVerificationV2): TransactionInstruction => ix(p, finalizeVerificationKeys(a), encodeFinalizeProgramDataVerificationV2(v));
export const buildObserveProgramDataFailureV2Instruction = (p: PublicKey, a: ObserveProgramDataFailureV2Accounts, v: ObserveProgramDataFailureV2): TransactionInstruction => ix(p, [ws(a.payer), ro(a.controllerConfig), ro(a.protocolGate), ro(a.primaryProposal), ro(a.programdataVerification), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.programdataObservation), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.authorityPda), ro(a.upgradeableLoader), rw(a.failureObservation), ro(a.systemProgram)], encodeObserveProgramDataFailureV2(v));
export const buildApproveUnfreezeV2Instruction = (p: PublicKey, a: ApproveUnfreezeV2Accounts, v: ApproveUnfreezeV2): TransactionInstruction => ix(p, [ro(a.controllerConfig), ro(a.policy), ro(a.currentCouncil), ro(a.protocolGate), rw(a.proposal), ro(a.poststateCheckpoint), ro(a.programdataVerification), ro(a.capacityPolicy), ro(a.currentDeployment), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.authorityPda), ro(a.upgradeableLoader), rs(a.seatAuthority)], encodeApproveUnfreezeV2(v));
export const buildExecuteUnfreezeV2Instruction = (p: PublicKey, a: ExecuteUnfreezeV2Accounts, v: ExecuteUnfreezeV2): TransactionInstruction => ix(p, [ro(a.controllerConfig), ro(a.policy), ro(a.currentCouncil), rw(a.protocolGate), rw(a.proposal), rw(a.linkedProposal), ro(a.poststateCheckpoint), ro(a.programdataVerification), ro(a.capacityPolicy), rw(a.currentDeployment), ro(a.targetProgram), ro(a.targetProgramdata), ro(a.authorityPda), ro(a.upgradeableLoader), ro(a.instructionsSysvar)], encodeExecuteUnfreezeV2(v));
